# Welcome to Jekyll!
#
# bundle exec jekyll serve
#
# bundle exec jekyll build
#

title: Express Gateway
email: info@express-gateway.io
description: A Microservices API Gateway Built on Express.JS
baseurl: "http://www.express-gateway.io/"
url: "http://www.express-gateway.io/"
twitter_username: express_gateway
encoding: UTF-8

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock

#syntax-highlighting
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

paginate: 5
paginate_path: "/blog/page-:num/"

permalink: /:title

collections:
  archives-month:
    output: true
    permalink: /blog/:path/
  archives-year:
    output: true
    permalink: /blog/:path/
  categories:
    output: true
    permalink: /blog/:path/

#Site specific config
include: ["_pages"]
