# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Express Gateway
email: info@express-gateway.io
description: A Microservices API Gateway Built on Express.JS
baseurl: "" # dev = "/" temp-prod ="http://bybrandonbrown.com/expressgateway/"
url: "http://bybrandonbrown.com/expressgateway" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xpressgateway
github_username:  expressgateway
encoding: UTF-8

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock

#syntax-highlighting
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

paginate: 5
paginate_path: "/blog/page-:num/"

permalink: /:title

collections:
  archives-month:
    output: true
    permalink: /blog/:path/
  archives-year:
    output: true
    permalink: /blog/:path/
  categories:
    output: true
    permalink: /blog/:path/

#Site specific config
include: ["_pages"]
