---
title: Express Gateway
timezone: UTC
collections:
  archives-month:
    title: Archives Month
    output: true
    permalink: "/blog/:path/"
  archives-year:
    title: Archives Year
    output: true
    permalink: "/blog/:path/"
  categories:
    title: Categories
    output: true
    permalink: "/blog/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@express-gateway.io
description: A Microservices API Gateway Built on Express.JS
url: https://www.express-gateway.io
twitter_username: express_gateway
encoding: UTF-8
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-redirect-from
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- vendor
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
paginate: 5
paginate_path: "/blog/page-:num/"
excerpt_separator: "<!--excerpt-->"
permalink: "/:title/"
include:
- _pages
